# Generated by Django 5.2.7 on 2025-10-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, choices=[('BLACK', 'Black'), ('WHITE', 'White'), ('RED', 'Red'), ('BLUE', 'Blue'), ('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('ORANGE', 'Orange'), ('PURPLE', 'Purple'), ('PINK', 'Pink'), ('BROWN', 'Brown'), ('GREY', 'Grey'), ('MULTICOLOR', 'Multicolor'), ('GOLD', 'Gold'), ('SILVER', 'Silver')], max_length=20, null=True),
        ),
    ]
