# Generated by Django 5.2.7 on 2025-10-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_productvariant_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('PAYPAL', 'PayPal')], max_length=20),
        ),
    ]
