# Generated by Django 5.2.7 on 2025-10-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='unique_post_bookmark',
        ),
    ]
