# Generated by Django 5.2.7 on 2025-10-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_bookmark_unique_post_bookmark'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_post_like',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_comment_like',
        ),
    ]
