# Generated by Django 5.2.7 on 2025-10-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_remove_like_unique_post_like_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
